import type { GsdRuntime } from "../types.js";

export function generateGsdScripts(
	runtimes: GsdRuntime[] | undefined,
): { sh: string; ps1: string } | undefined {
	if (!runtimes || runtimes.length === 0) {
		return undefined;
	}

	// Map runtimes to their corresponding CLI flags for GSD installer
	const flags = runtimes.map((r) => `--${r}`).join(" ");

	const sh = `#!/usr/bin/env bash
# Automatically generated by Better-OpenClaw

if ! command -v npx &> /dev/null; then
    echo "Error: Node.js (npx) is not installed. Please install Node.js."
    exit 1
fi

echo "Installing Get-Shit-Done workflows for requested runtimes: ${runtimes.join(", ")}"
npx yes | npx get-shit-done-cc@latest --local ${flags}

echo "GSD Integration Complete!"
echo "Check the injected folders matching your target platform (e.g. .claude, .codex)."
`;

	const ps1 = `# Automatically generated by Better-OpenClaw

if (!(Get-Command npx -ErrorAction SilentlyContinue)) {
    Write-Error "Error: Node.js (npx) is not installed. Please install Node.js."
    exit 1
}

Write-Host "Installing Get-Shit-Done workflows for requested runtimes: ${runtimes.join(", ")}"
npx get-shit-done-cc@latest --local ${flags}

Write-Host "GSD Integration Complete!"
Write-Host "Check the injected folders matching your target platform (e.g. .claude, .codex)."
`;

	return { sh, ps1 };
}
