/**
 * Generates Grafana provisioning configuration files.
 *
 * Returns a map of file paths (relative to project root) to file contents.
 * Includes datasource provisioning YAML for the Prometheus connection.
 */
export function generateGrafanaConfig(): Record<string, string> {
	const files: Record<string, string> = {};

	// ── Datasource Provisioning ─────────────────────────────────────────────

	files["config/grafana/provisioning/datasources/prometheus.yml"] =
		`# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Datasource Provisioning — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

apiVersion: 1

datasources:
  # Prometheus — primary metrics datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: ""
    version: 1
`;

	// ── Dashboard Provisioning ───────────────────────────────────────────────

	files["config/grafana/provisioning/dashboards/default.yml"] =
		`# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Dashboard Provisioning — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

apiVersion: 1

providers:
  - name: "OpenClaw Dashboards"
    orgId: 1
    folder: "OpenClaw"
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
`;

	// ── Grafana Configuration (grafana.ini overrides) ────────────────────────

	files["config/grafana/grafana.ini"] =
		`# ═══════════════════════════════════════════════════════════════════════════════
# Grafana Configuration — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

[server]
root_url = %(protocol)s://%(domain)s/

[security]
# Admin credentials are set via environment variables:
#   GF_SECURITY_ADMIN_USER
#   GF_SECURITY_ADMIN_PASSWORD

[auth.anonymous]
enabled = false

[dashboards]
default_home_dashboard_path = /var/lib/grafana/dashboards/home.json

[alerting]
enabled = true

[unified_alerting]
enabled = true

[log]
mode = console
level = info
`;

	return files;
}

/**
 * Generates a Grafana dashboard JSON for the OpenClaw stack overview.
 *
 * The dashboard includes:
 * - Service Health (stat panel)
 * - Memory Usage (gauge)
 * - Request Rate (graph)
 *
 * Uses Prometheus as the datasource.
 */
export function generateGrafanaDashboard(): string {
	const dashboard = {
		annotations: { list: [] },
		editable: true,
		fiscalYearStartMonth: 0,
		graphTooltip: 1,
		links: [],
		panels: [
			{
				// ── Service Health (stat panel) ──
				id: 1,
				title: "Service Health",
				type: "stat",
				gridPos: { h: 8, w: 8, x: 0, y: 0 },
				datasource: { type: "prometheus", uid: "prometheus" },
				targets: [
					{
						expr: 'count(up{job=~".+"} == 1)',
						legendFormat: "Healthy Services",
						refId: "A",
					},
				],
				fieldConfig: {
					defaults: {
						thresholds: {
							mode: "absolute",
							steps: [
								{ color: "red", value: null },
								{ color: "yellow", value: 1 },
								{ color: "green", value: 3 },
							],
						},
						color: { mode: "thresholds" },
						mappings: [],
					},
					overrides: [],
				},
				options: {
					reduceOptions: {
						values: false,
						calcs: ["lastNotNull"],
						fields: "",
					},
					orientation: "auto",
					textMode: "auto",
					colorMode: "background",
					graphMode: "none",
					justifyMode: "auto",
				},
			},
			{
				// ── Memory Usage (gauge) ──
				id: 2,
				title: "Memory Usage",
				type: "gauge",
				gridPos: { h: 8, w: 8, x: 8, y: 0 },
				datasource: { type: "prometheus", uid: "prometheus" },
				targets: [
					{
						expr: "sum(container_memory_usage_bytes) / sum(machine_memory_bytes) * 100",
						legendFormat: "Memory %",
						refId: "A",
					},
				],
				fieldConfig: {
					defaults: {
						thresholds: {
							mode: "absolute",
							steps: [
								{ color: "green", value: null },
								{ color: "yellow", value: 60 },
								{ color: "red", value: 85 },
							],
						},
						color: { mode: "thresholds" },
						min: 0,
						max: 100,
						unit: "percent",
						mappings: [],
					},
					overrides: [],
				},
				options: {
					reduceOptions: {
						values: false,
						calcs: ["lastNotNull"],
						fields: "",
					},
					orientation: "auto",
					showThresholdLabels: false,
					showThresholdMarkers: true,
				},
			},
			{
				// ── Request Rate (graph / timeseries) ──
				id: 3,
				title: "Request Rate",
				type: "timeseries",
				gridPos: { h: 8, w: 8, x: 16, y: 0 },
				datasource: { type: "prometheus", uid: "prometheus" },
				targets: [
					{
						expr: 'sum(rate(http_requests_total{job=~".+"}[5m])) by (job)',
						legendFormat: "{{job}}",
						refId: "A",
					},
				],
				fieldConfig: {
					defaults: {
						color: { mode: "palette-classic" },
						custom: {
							axisBorderShow: false,
							axisCenteredZero: false,
							axisColorMode: "text",
							axisLabel: "req/s",
							drawStyle: "line",
							fillOpacity: 10,
							gradientMode: "none",
							lineInterpolation: "smooth",
							lineWidth: 2,
							pointSize: 5,
							showPoints: "auto",
							spanNulls: false,
							stacking: { group: "A", mode: "none" },
						},
						mappings: [],
						thresholds: {
							mode: "absolute",
							steps: [{ color: "green", value: null }],
						},
						unit: "reqps",
					},
					overrides: [],
				},
				options: {
					legend: { calcs: [], displayMode: "list", placement: "bottom" },
					tooltip: { mode: "multi", sort: "desc" },
				},
			},
		],
		schemaVersion: 39,
		tags: ["openclaw"],
		templating: { list: [] },
		time: { from: "now-1h", to: "now" },
		timepicker: {},
		timezone: "browser",
		title: "OpenClaw Stack Overview",
		uid: "openclaw-stack-overview",
	};

	return JSON.stringify(dashboard, null, 2);
}
