import type { ResolverOutput } from "../types.js";

/**
 * Well-known metrics endpoints for services.
 *
 * Services that expose Prometheus-compatible metrics are listed here
 * with their metrics path and port.
 */
const metricsEndpoints: Record<string, { path: string; port: number }> = {
	redis: { path: "/metrics", port: 9121 },
	postgresql: { path: "/metrics", port: 9187 },
	minio: { path: "/minio/v2/metrics/cluster", port: 9000 },
	n8n: { path: "/metrics", port: 5678 },
	grafana: { path: "/metrics", port: 3000 },
	caddy: { path: "/metrics", port: 2019 },
	traefik: { path: "/metrics", port: 8082 },
	qdrant: { path: "/metrics", port: 6333 },
	"uptime-kuma": { path: "/metrics", port: 3001 },
	ollama: { path: "/metrics", port: 11434 },
};

/**
 * Generates a Prometheus configuration YAML file with scrape configs
 * for all services that expose metrics endpoints.
 *
 * @param resolved - The resolved service configuration
 * @returns The prometheus.yml content as a string
 */
export function generatePrometheusConfig(resolved: ResolverOutput): string {
	const sections: string[] = [];

	// ── Header ──────────────────────────────────────────────────────────────

	sections.push(`# ═══════════════════════════════════════════════════════════════════════════════
# Prometheus Configuration — Auto-generated by OpenClaw
# ═══════════════════════════════════════════════════════════════════════════════

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# ─── Scrape Configs ──────────────────────────────────────────────────────────

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: "prometheus"
          component: "monitoring"`);

	// ── Service Scrape Configs ───────────────────────────────────────────────

	for (const { definition } of resolved.services) {
		// Skip prometheus itself (already included above)
		if (definition.id === "prometheus") continue;

		const endpoint = metricsEndpoints[definition.id];
		if (!endpoint) continue;

		sections.push(`
  # ${definition.icon} ${definition.name}
  - job_name: "${definition.id}"
    metrics_path: "${endpoint.path}"
    static_configs:
      - targets: ["${definition.id}:${endpoint.port}"]
        labels:
          service: "${definition.id}"
          component: "${definition.category}"`);
	}

	// ── OpenClaw Gateway Metrics ────────────────────────────────────────────

	sections.push(`
  # 🐾 OpenClaw Gateway
  - job_name: "openclaw-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["openclaw:18789"]
        labels:
          service: "openclaw"
          component: "core"`);

	sections.push("");

	return sections.join("\n");
}
