import type { ResolverOutput } from "../types.js";

export interface TraefikGeneratorOutput {
	staticConfig: string;
	serviceLabels: Map<string, Record<string, string>>;
}

/**
 * Generates Traefik configuration: a static config YAML file and per-service
 * Docker labels for automatic service discovery and reverse proxy routing.
 *
 * @param resolved - The resolved service configuration
 * @param domain - The main domain for routing (e.g. "example.com")
 * @returns Static config content and a map of serviceId → Docker labels
 */
export function generateTraefikConfig(
	resolved: ResolverOutput,
	domain: string,
): TraefikGeneratorOutput {
	const staticConfig = generateStaticConfig(domain);
	const serviceLabels = new Map<string, Record<string, string>>();

	// Per-service labels for exposed ports
	for (const { definition } of resolved.services) {
		if (definition.id === "traefik" || definition.id === "caddy") continue;

		const exposedPorts = definition.ports.filter((p) => p.exposed);
		if (exposedPorts.length === 0) continue;

		const primaryPort = exposedPorts[0]!;
		const routerName = definition.id.replace(/-/g, "");

		const labels: Record<string, string> = {
			"traefik.enable": "true",
			// HTTPS router
			[`traefik.http.routers.${routerName}.rule`]: `Host(\`${definition.id}.${domain}\`)`,
			[`traefik.http.routers.${routerName}.entrypoints`]: "websecure",
			[`traefik.http.routers.${routerName}.tls.certresolver`]: "letsencrypt",
			[`traefik.http.services.${routerName}.loadbalancer.server.port`]: String(
				primaryPort.container,
			),
			// HTTP → HTTPS redirect
			[`traefik.http.routers.${routerName}-http.rule`]: `Host(\`${definition.id}.${domain}\`)`,
			[`traefik.http.routers.${routerName}-http.entrypoints`]: "web",
			[`traefik.http.routers.${routerName}-http.middlewares`]: "redirect-to-https",
		};

		serviceLabels.set(definition.id, labels);
	}

	// Gateway gets the root domain
	serviceLabels.set("openclaw-gateway", {
		"traefik.enable": "true",
		"traefik.http.routers.gateway.rule": `Host(\`${domain}\`)`,
		"traefik.http.routers.gateway.entrypoints": "websecure",
		"traefik.http.routers.gateway.tls.certresolver": "letsencrypt",
		"traefik.http.services.gateway.loadbalancer.server.port": "18789",
		"traefik.http.routers.gateway-http.rule": `Host(\`${domain}\`)`,
		"traefik.http.routers.gateway-http.entrypoints": "web",
		"traefik.http.routers.gateway-http.middlewares": "redirect-to-https",
	});

	// Global redirect middleware on the Traefik service itself
	serviceLabels.set("traefik", {
		"traefik.enable": "true",
		"traefik.http.middlewares.redirect-to-https.redirectscheme.scheme": "https",
		"traefik.http.middlewares.redirect-to-https.redirectscheme.permanent": "true",
	});

	return { staticConfig, serviceLabels };
}

function generateStaticConfig(domain: string): string {
	return `# Traefik Static Configuration — Auto-generated by OpenClaw
# Domain: ${domain}

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: openclaw-network

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@${domain}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
`;
}
